### PR TITLE
Fix ReadLoud again

### PR DESCRIPTION
**Pull request by Crawlerop**

### CODE REVIEW

**Comment by 790505** [comment]
troublemaker

**Comment by 790505** [comment]
caillou

**Comment by Evanissmaet** [comment]
Caillou

**Review by Evanissmaet — COMMENTED** [review]
Fix

**Review by Evanissmaet — COMMENTED** [review]
Fix Rls Right now

**Review by Evanissmaet — COMMENTED** [review]
Idk

**Pull request merged**
