### PR TITLE
Add save starters

### PR DESCRIPTION
**Pull request by josephcrosmanplays532**

### CODE REVIEW

**Comment by zoccorus** [comment]
no

**Comment by josephcrosmanplays532** [comment]
> no

Why not? The save starters must work in wrapper offline 1.3.0

**Comment by imageny** [comment]
That's planned for a later update. Some of the devs are kinda lazy and, while it works similar to saving movies, I myself have not been able to figure out how to get the starters fully working

**Comment by josephcrosmanplays532** [comment]
> That's planned for a later update. Some of the devs are kinda lazy and, while it works similar to saving movies, I myself have not been able to figure out how to get the starters fully working

Okay then.

**Pull request closed without merging**
