### PR TITLE
ur forgot

### PR DESCRIPTION
**Pull request by zoccorus**

### CODE REVIEW

**Comment by Thunderzapper** [comment]
huh?

**Comment by zoccorus** [comment]
env_backup.json

**Comment by narutofan420** [comment]
We're not responsible for people ruining their env.json.

**Comment by zoccorus** [comment]
GRRR WE WANT ENV BACKUP

**Comment by narutofan420** [comment]
_We're not responsible for people ruining their env.json._

**Comment by imageny** [comment]
https://youtu.be/yqTjKhYh4fs?t=15

**Pull request closed without merging**
