### PR TITLE
Added Custom Assets

### PR DESCRIPTION
**Pull request by zoccorus**
link
https://www.mediafire.com/file/jif3joe34c2uar6/Newer_Assets_15.0.rar/file
copy files and paste to "server/store/3a981f5cb2739137/cc_store/family".

### CODE REVIEW

**Comment by narutofan420** [comment]
We don't need custom assets. You can DIY.

**Comment by zoccorus** [comment]
😡

**Comment by zoccorus** [comment]
🖕

**Comment by zoccorus** [comment]
@narutofan420 DIE!!!

**Comment by zoccorus** [comment]
💔

**Comment by zoccorus** [comment]
FUCK YOU NIGGA! WERE NOT FRIENDS! GO FUCK YOURSELF BITCH YOU DIE!!!

**Comment by zoccorus** [comment]
> We don't need custom assets. You can DIY.

WHY YOU GO HATE ME BECAUS

> We don't need custom assets. You can DIY.

https://www.voicy.network/Content/Clips/Sound/547d2d42-c646-450d-93f0-67510b95b135.mp3

**Comment by narutofan420** [comment]
Please stop.

**Comment by zoccorus** [comment]
> Please stop.

dont force me or you will grounded for +639212965225 numbers.

**Pull request closed without merging**
